-*- encoding: utf-8; indent-tabs-mode: nil -*-

=encoding utf8

=head1 FRENCH REVOLUTIONARY CALENDAR

=head2 PURPOSE

This repository hosts  a Pascal program which allows you  to convert dates from
the Gregorian  calendar to  the French Revolutionary  Calendar or in  the other
way.

User documentation can be read with:

  perldoc calfr.p

(yes! It works!  Provided the source code file is  available. If the executable
is shipped without the source code file, you are out of luck.)

French  speaking user  documentation can  be read  by running  the  program and
asking C<1> for the embedded demo.

=head2 PASCAL

The compiler used is B<Free Pascal> version 3.0.4.

See L<https://www.freepascal.org/>.

=head2 REMARK

If you read this page because you noticed that I had some Github activity in
L<1983|https://github.com/jforget?tab=overview&from=1983-12-01&to=1983-12-31>
and L<1984|https://github.com/jforget?tab=overview&from=1983-12-01&to=1983-12-31>,
you might be interested in reading
L<this other project|https://github.com/jforget/Perl-fixed-width-char-human-recognition/blob/master/description/description.pod>
(sorry, French only for the moment).

=head2 LICENSE

The program is licensed under the same terms as Perl 5: GPL and Artistic
License. For more details, please read the F<LICENSE> file in this repository.
